 #ifndef CONFIG_H
 #define CONFIG_H

 #cmakedefine INDICATORNAME "@INDICATORNAME@"
 #cmakedefine DATADIR "@DATADIR@"
 #cmakedefine PKGDATADIR "@PKGDATADIR@"
 #cmakedefine AYANATAINDICATORDIR "@AYANATAINDICATORDIR@"
 #cmakedefine GETTEXT_PACKAGE "@GETTEXT_PACKAGE@"

 #endif // CONFIG_H
